DERP-816 - Refactored entity bundle config.
GreaterLondonAuthority/gla_core_profile pull request #101
Opened 2021-09-03 15:56 UTC by lukewhitmore

Issue [here](https://london.atlassian.net/browse/DERP-816)

N/B more PRs will be released for other bundle types.

2021-09-03 15:57 UTC, lukewhitmore commented
@philwolstenholme This still has a breaking dependency on default content. What's the best way of addressing this?

2021-09-06 09:14 UTC, Fullstack-Lincoln commented on config/install/core.entity_form_display.media.image.default.yml
> +uuid: eb7eb730-29b5-46de-8dd6-100cc2273046
Can you remove the uuid please?

2021-09-06 09:14 UTC, Fullstack-Lincoln commented on config/install/core.entity_form_display.media.image.default.yml
> +  default_config_hash: iwj0z6LJBeD5LLt0KrCsoIPmUbRlrEcfNgxjDgN_Dlc
Can you remove these lines please?

2021-09-06 09:16 UTC, Fullstack-Lincoln commented on config/install/media.type.image.yml
> +  source_field: field_bynder_id
No issue with this line but I'm just wondering as a result of this change might we need to change other components that use images and this source field?

2021-09-06 09:16 UTC, Fullstack-Lincoln approved these changes

2021-09-06 09:17 UTC, Fullstack-Lincoln requested changes

2021-09-06 09:17 UTC, Fullstack-Lincoln commented on config/install/core.entity_form_display.media.image.default.yml
> +uuid: eb7eb730-29b5-46de-8dd6-100cc2273046
This

2021-09-08 17:14 UTC, closed without merging

2021-09-08 18:14 UTC, lukewhitmore commented
Closed this PR it contained an API secret which has been revoked.