Feature/derp 240 manage layout row component
GreaterLondonAuthority/gla_core_profile pull request #113
Opened 2021-09-13 17:21 UTC by Fullstack-Lincoln

2021-09-14 10:03 UTC, philwolstenholme commented
Linc and I spoke about this and we'll wait a bit longer to merge it in as Linc is still working on the backend display

2021-09-14 13:53 UTC, VincenzoGambino commented on modules/gla_core_layout/gla_core_layout.module
> +      unset($field_widget_complete_form['widget']['add_more']['operations']['#links']['add_more_button_layout_row']);
Could this be achieved using ['#access'] = FALSE; ?

2021-09-14 15:32 UTC, Fullstack-Lincoln commented on modules/gla_core_layout/gla_core_layout.module
> +      unset($field_widget_complete_form['widget']['add_more']['operations']['#links']['add_more_button_layout_row']);
Ermmm I don't know 100% yet, this code won't be in use yet until we build the tabs component....

2021-09-15 09:36 UTC, philwolstenholme commented on modules/gla_core_layout/gla_core_layout.module
> +      unset($field_widget_complete_form['widget']['add_more']['operations']['#links']['add_more_button_layout_row']);
I don't think we're are going to have a Tab component @Fullstack-Lincoln so I would delete this function, we shouldn't copy across code that we don't know for sure is going to be used in the future.

2021-09-15 09:38 UTC, philwolstenholme requested changes

2021-09-15 09:38 UTC, philwolstenholme commented on modules/gla_core_layout/src/Plugin/Layout/MultiWidthSpacingLayout.php
> +    // Spacing, vertical and horizontal alignment use Bootstrap classes to save
Swap these Bootstrap mentions for Tailwind I think @Fullstack-Lincoln?

2021-09-15 09:40 UTC, Fullstack-Lincoln commented on modules/gla_core_layout/src/Plugin/Layout/MultiWidthSpacingLayout.php
> +    // Spacing, vertical and horizontal alignment use Bootstrap classes to save
Done

2021-09-15 09:46 UTC, philwolstenholme approved these changes

2021-09-15 09:46 UTC, merged