Feature/derp 714 bynder integration
GreaterLondonAuthority/gla_core_profile pull request #122
Opened 2021-09-16 13:23 UTC by lukewhitmore

Issue [here](https://london.atlassian.net/browse/DERP-714)

2021-09-16 13:52 UTC, VincenzoGambino commented on composer.json
> +        "md-systems/bynder_local": "dev-task/DERP-714-update-bynder-local-to-allow-field-for-local-storage-to-be-set",
Should this be against a tag or main branch?

2021-09-16 13:52 UTC, VincenzoGambino commented on config/install/field.field.paragraph.page_section.field_p_ps_components.yml
> +      blockquote: blockquote
Is this an intruder?

2021-09-16 13:52 UTC, VincenzoGambino commented on config/install/user.role.anonymous.yml
> -  - 'view paragraph content gmap'
Are this being removed on purpose?

2021-09-16 13:52 UTC, VincenzoGambino commented on config/install/user.role.authenticated.yml
> -  - 'view paragraph content gmap'
Are this being removed on purpose?

2021-09-16 14:01 UTC, lukewhitmore commented on composer.json
> +        "md-systems/bynder_local": "dev-task/DERP-714-update-bynder-local-to-allow-field-for-local-storage-to-be-set",
Once it's merged I'll update this, but for now I set to a branch to avoid blocking.

2021-09-16 14:01 UTC, lukewhitmore commented on config/install/field.field.paragraph.page_section.field_p_ps_components.yml
> +      blockquote: blockquote
Yes! Thanks

2021-09-16 14:02 UTC, lukewhitmore commented on config/install/user.role.anonymous.yml
> -  - 'view paragraph content gmap'
No .. good spot .. thanks

2021-09-16 14:02 UTC, lukewhitmore commented on config/install/user.role.authenticated.yml
> -  - 'view paragraph content gmap'
Likewise

2021-09-16 14:02 UTC, lukewhitmore commented on config/install/user.role.authenticated.yml
> -  - 'view paragraph content gmap'
(Good spot .. thanks)

2021-09-16 14:16 UTC, joz-cti approved these changes

2021-09-17 15:22 UTC, Fullstack-Lincoln commented on config/install/core.entity_form_display.paragraph.cta.default.yml
> +langcode: en
This file needs removing because it's an estate component

2021-09-17 15:23 UTC, Fullstack-Lincoln commented on config/install/core.entity_view_display.paragraph.cta.default.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:24 UTC, Fullstack-Lincoln commented on config/install/field.field.node.generic_content.field_c_gc_page_components.yml
> +        enabled: false
This reference to CTA should be removed

2021-09-17 15:25 UTC, Fullstack-Lincoln commented on config/install/field.field.paragraph.cta.field_p_cta_heading.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:25 UTC, Fullstack-Lincoln commented on config/install/field.field.paragraph.cta.field_p_cta_reverse_layout.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:25 UTC, Fullstack-Lincoln commented on config/install/field.field.paragraph.hero_header.field_p_hh_components.yml
> +        enabled: false
This reference should be removed

2021-09-17 15:25 UTC, Fullstack-Lincoln commented on config/install/field.storage.paragraph.field_p_cta_heading.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:25 UTC, Fullstack-Lincoln commented on config/install/field.storage.paragraph.field_p_cta_reverse_layout.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_lg.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_lg_2x.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_md.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_md_2x.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_sm.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:26 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_sm_2x.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:27 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_xl.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:27 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_xl_2x.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:27 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_xxl.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:27 UTC, Fullstack-Lincoln commented on config/install/image.style.cta_component_xxl_2x.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:27 UTC, Fullstack-Lincoln commented on config/install/responsive_image.styles.cta_component.yml
> +langcode: en
This file shouldn't be here because CTA is part of the estate

2021-09-17 15:31 UTC, VincenzoGambino requested changes

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.field.node.generic_content.field_c_gc_page_components.yml
> +        enabled: false
The CTA component should be included only in the lgov repo.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.field.paragraph.cta.field_p_cta_heading.yml
> +langcode: en
CTA field to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.field.paragraph.cta.field_p_cta_reverse_layout.yml
> +langcode: en
CTA field to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.field.paragraph.hero_header.field_p_hh_components.yml
> +        enabled: false
The CTA component should be included only in the lgov repo.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.storage.paragraph.field_p_cta_heading.yml
> +langcode: en
CTA field to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/field.storage.paragraph.field_p_cta_reverse_layout.yml
> +langcode: en
CTA field to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_lg.yml
> +langcode: en
CTA reference  to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_lg_2x.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_md.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_md_2x.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_sm.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_sm_2x.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_xl.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_xl_2x.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_xxl.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/image.style.cta_component_xxl_2x.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/responsive_image.styles.cta_component.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/core.entity_form_display.paragraph.cta.default.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 15:31 UTC, VincenzoGambino commented on config/install/core.entity_view_display.paragraph.cta.default.yml
> +langcode: en
CTA reference to be removed.

2021-09-17 16:01 UTC, lukewhitmore commented on config/install/field.storage.paragraph.field_p_cta_heading.yml
> +langcode: en
@Fullstack-Lincoln Blockquote too?

2021-09-17 16:01 UTC, lukewhitmore commented on config/install/field.field.paragraph.hero_header.field_p_hh_components.yml
> +        enabled: false
@Fullstack-Lincoln Blockquote too?

2021-09-17 16:02 UTC, lukewhitmore commented on config/install/field.field.node.generic_content.field_c_gc_page_components.yml
> +        enabled: false
@Fullstack-Lincoln Blockquote too?

2021-09-17 16:25 UTC, Fullstack-Lincoln approved these changes

2021-09-19 14:39 UTC, VincenzoGambino approved these changes

2021-09-20 08:41 UTC, merged