DERP-226 manage content listing component.
GreaterLondonAuthority/gla_core_profile pull request #89
Opened 2021-08-27 15:36 UTC by VincenzoGambino

Added content listing component.
Created new custom module gla_content_listing.

2021-09-01 12:04 UTC, Fullstack-Lincoln commented on config/install/field.field.paragraph.page_section.field_p_ps_components.yml
> +    - paragraphs.paragraphs_type.blockquote
Blockquote shouldn't be her because it's added onto the page section through the blockquote estate module

2021-09-01 12:07 UTC, Fullstack-Lincoln commented
It looks like you're missing the view content listing permissions on the anonymous and authenticated roles.

2021-09-02 15:29 UTC, philwolstenholme commented
I think the view permissions are still missing

2021-09-03 10:23 UTC, lukewhitmore requested changes
Hey there — could we have a chat as a group re. the automated solution please. What you've done is great .. but we might need to diverge from the Voyager approach

2021-09-03 10:23 UTC, lukewhitmore commented on modules/gla_core_content_listing/src/Plugin/ContentListingType/AutomatedContentListing.php
> +      $query->condition('field_tags', $tags, 'IN');
Hi @VincenzoGambino  I've been chatting to Joz about this; it sounds like we'll need to extend this solution so it's more flexible.

At the moment, the filtering via taxonomy term is limited to `field_tags` which is one vocabulary.

We need to be able to potentially filter by all of the vocabularies available via the selected content type.

Our worry is that we're actually recreating views; but without benefits of the cache layer etc.

2021-09-03 10:25 UTC, lukewhitmore commented on modules/gla_core_content_listing/src/Plugin/ContentListingType/AutomatedContentListing.php
> +      $query->condition('field_tags', $tags, 'IN');
@philwolstenholme would be good to get your thoughts here too!

2021-09-03 11:57 UTC, VincenzoGambino commented on modules/gla_core_content_listing/src/Plugin/ContentListingType/AutomatedContentListing.php
> +      $query->condition('field_tags', $tags, 'IN');
Hi,

Sorry, I have just finished #631 which is the Related content component.

We can have a chat this afternoon.

2021-09-06 15:12 UTC, VincenzoGambino commented on modules/gla_core_content_listing/src/Plugin/ContentListingType/AutomatedContentListing.php
> +      $query->condition('field_tags', $tags, 'IN');
The vocabulary reference is not hardcoded, only the field name as the content_types. We can add more vocabulary in the field settings.

2021-09-08 12:52 UTC, lukewhitmore commented on config/install/views.view.content_listing_taxonomy_reference.yml
> +          perm: 'access content'
@VincenzoGambino I wonder whether this should be changed. AFAIK 'access content' is view content. Should be be changed to be less permissive?

2021-09-08 13:32 UTC, VincenzoGambino commented on config/install/views.view.content_listing_taxonomy_reference.yml
> +          perm: 'access content'
The most restrictive would be the edit paragraph content listing permission. The same will apply to the Related Items component. As long as we use this display only for content listing it should be an issue.

2021-09-13 09:59 UTC, philwolstenholme submitted a review, later dismissed
~@VincenzoGambino there are a few leftovers from the related content work here, we're using `field_p_ri_listing_type` instead of `field_p_cl_listing_type` in a few places~

Edit: just fixed these myself for you

2021-09-13 09:59 UTC, philwolstenholme commented on modules/gla_core_content_listing/gla_core_content_listing.module
> +    $listing_type = $entity->get('field_p_ri_listing_type')->getValue();
@VincenzoGambino  I think this field name might be wrong?

```suggestion
    $listing_type = $entity->get('field_p_cl_listing_type')->getValue();
```

2021-09-13 09:59 UTC, philwolstenholme commented on modules/gla_core_content_listing/gla_core_content_listing.module
> + * Alter the paragraph form depending on the field_p_ri_listing_type field.
```suggestion
 * Alter the paragraph form depending on the field_p_cl_listing_type field.
```

2021-09-13 09:59 UTC, philwolstenholme commented on modules/gla_core_content_listing/gla_core_content_listing.module
> + * See config/install/field.storage.paragraph.field_p_ri_listing_type.yml
```suggestion
 * See config/install/field.storage.paragraph.field_p_cl_listing_type.yml
```

2021-09-14 09:53 UTC, Fullstack-Lincoln commented on config/install/core.entity_view_display.node.generic_content.card.yml
> +uuid: ba82d65a-5115-4813-b9a0-cd5a479cf036
@VincenzoGambino Can you remove this UUID please?

2021-09-14 09:54 UTC, Fullstack-Lincoln commented on config/install/core.entity_view_mode.node.full.yml
> +uuid: f5a345a8-8c8b-4a49-a3cd-846841bb21a1
Can you remove this UUID please?

2021-09-14 09:54 UTC, Fullstack-Lincoln commented on config/install/core.entity_view_mode.node.full.yml
> +  default_config_hash: ElrtInxGjZd7GaapJ5O9n-ugi2hG2IxFivtgn0tHOsk
Can you remove these 2 lines please?

2021-09-14 13:13 UTC, VincenzoGambino commented on config/install/core.entity_view_display.node.generic_content.card.yml
> +uuid: ba82d65a-5115-4813-b9a0-cd5a479cf036
Removed.

2021-09-14 13:14 UTC, VincenzoGambino commented on config/install/core.entity_view_mode.node.full.yml
> +  default_config_hash: ElrtInxGjZd7GaapJ5O9n-ugi2hG2IxFivtgn0tHOsk
Removed

2021-09-15 10:46 UTC, Fullstack-Lincoln approved these changes

2021-09-15 10:46 UTC, merged